version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/dlminvestments/nodejs-docs-samples"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest",
    "mocha",
    "jasmine",
    "jquery",
    "mongo"
  ]
  plugins = [
    "react",
    "vue",
    "ember",
    "meteor",
    "angularjs",
    "angular"
  ]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "shell"
enabled = true
