---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'plugin:promise'
  - prettier
env:
  mocha: true
plugins:
  - node
  - prettier
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-console: off
  node/no-missing-require: off
  node/no-unpublished-require: off
  prefer-const: error
  no-var: error
  prefer-arrow-callback: error
  no-throw-literal: error
  require-await: error
  prefer-await-to-then: error
  prefer-destructuring: error