---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'prettier'
env:
  mocha: true
plugins:
  - node
  - prettier
  - promise
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-console: off
  node/no-missing-require: off
  node/no-unpublished-require: off
  prefer-const: error
  no-var: error
  prefer-arrow-callback: error
  no-throw-literal: warn
  require-await: warn
  promise/prefer-await-to-then: warn
  promise/no-nesting: warn
  prefer-destructuring: warn
  func-style:
    - 1
    - expression
    - allowArrowFunctions: true
