---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'prettier'
env:
  mocha: true
plugins:
  - node
  - prettier
  - promise
rules:
  require-atomic-updates: warn
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-console: off
  node/no-missing-require: off
  node/no-unpublished-require: off
  prefer-const: error
  no-var: error
  prefer-arrow-callback: error
  no-throw-literal: error
  require-await: error
  promise/prefer-await-to-then: error
  promise/no-nesting: error
  prefer-destructuring: error
  prefer-template: error
  func-style:
    - error
    - expression
    - allowArrowFunctions: true
