---
rules:
  no-console: off
  node/no-missing-import:
    allowModules:
      - p-queue
  node/no-unsupported-features/es-syntax: off
  node/no-unsupported-features/node-builtins: off
parserOptions:
  ecmaVersion: 11