#!/usr/bin/env node

/**
 * Copyright 2017, Google, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const execSync = require('child_process').execSync;
const path = require('path');

let localPath = process.argv.slice(2)[0] || process.cwd();

if (!path.isAbsolute(localPath)) {
  localPath = path.join(process.cwd(), localPath);
}

const branch = execSync('git rev-parse --abbrev-ref HEAD').toString().trim();

const command = `samples test build -l=${localPath} --async`;
console.log(`Command: ${command}`);

if (branch === 'master') {
  execSync(command, {
    stdio: 'inherit'
  });
} else {
  const numChangedFiles = execSync('git diff-tree --no-commit-id --name-status -r HEAD')
    .toString()
    .trim()
    .split('\n')
    .filter((line) => line)
    .filter((line) => !line.startsWith('D'))
    .map((line) => line.replace(/^\w(\s)+/, ''))
    .map((line) => path.resolve(line))
    .filter((line) => line.includes(localPath))
    .length;

  if (numChangedFiles) {
    execSync(command, {
      stdio: 'inherit'
    });
  } else {
    console.log(`Skipping ${localPath}`);
  }
}
