#!/usr/bin/env node

// Copyright 2016, Google, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

require('shelljs/global');

uninstallForDirectories('appengine');
uninstallForDirectory('bigquery');
uninstallForDirectory('computeengine');
uninstallForDirectory('datastore');
uninstallForDirectory('debugger');
uninstallForDirectories('functions');
uninstallForDirectory('language');
uninstallForDirectory('logging');
uninstallForDirectory('monitoring');
uninstallForDirectory('prediction');
uninstallForDirectory('pubsub');
uninstallForDirectory('speech');
uninstallForDirectory('storage');
uninstallForDirectory('trace');
uninstallForDirectory('vision');

cd('functions/ocr/app');
rm('-rf', 'node_modules');
cd('../../..');

/**
 * unInstall NPM dependencies within a single directory.
 *
 * @param {string} directory The name of the directory in which to uninstall dependencies.
 */
function uninstallForDirectory(directory) {
  // Move into the directory
  cd(directory);

  // Uninstall dependencies
  console.log(directory + '...uninstalling dependencies');
  rm('-rf', 'node_modules');
  console.log(directory + '...done');

  // Move out of the directory
  cd('..');
}

/**
 * Recursively uninstall NPM dependencies within a single directory.
 *
 * @param {string} directory The name of the directory in which to recursively uninstall dependencies.
 */
function uninstallForDirectories(directory) {
  // Move into the directory
  cd(directory);

  // List the files in the directory
  ls('-dl', '*')
    .filter(function (file) {
      // Find the directories within the directory
      return file.isDirectory();
    })
    .forEach(function (file) {
      // Move into the sub-directory
      cd(file.name);

      // Uninstall dependencies
      console.log(directory + '/' + file.name + '...uninstalling dependencies');
      rm('-rf', 'node_modules');
      console.log(directory + '/' + file.name + '...done');

      // Move out of the sub-directory
      cd('..');
    });

  // Move out of the directory
  cd('..');
}
