#!/usr/bin/env node

// Copyright 2016, Google, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

var async = require('async');
var path = require('path');

require('shelljs/global');

// Check NPM dependencies, in up to 7 directories at a time
var queue = async.queue(function (directory, callback) {
  checkForDirectory(directory, callback);
}, 1);

queueDirectories('appengine');
queue.push('bigquery');
queue.push('computeengine');
queue.push('datastore');
queue.push('debugger');
queue.push('dns');
queueDirectories('functions');
queue.push('functions/ocr/app');
queue.push('language');
queue.push('logging');
queue.push('monitoring');
queue.push('prediction');
queue.push('pubsub');
queue.push('resource');
queue.push('speech');
queue.push('storage');
queue.push('trace');
queue.push('translate');
queue.push('vision');

/**
 * Check NPM dependencies within a single directory.
 *
 * @param {string} directory The name of the directory in which to check dependencies.
 * @param {function} callback The callback function.
 */
function checkForDirectory(directory, callback) {
  console.log(directory + '...checking dependencies');
  exec('npm outdated', {
    async: true,
    cwd: path.join(__dirname, '../', directory)
  }, callback);
}

/**
 * Recursively check NPM dependencies within a single directory.
 *
 * @param {string} directory The name of the directory in which to recursively check dependencies.
 */
function queueDirectories(directory) {
  // Move into the directory
  cd(directory);

  // List the files in the directory
  ls('-dl', '*')
    .filter(function (file) {
      // Find the directories within the directory
      return file.isDirectory() && file.name !== 'test' && file.name !== 'system-test';
    })
    .forEach(function (file) {
      queue.push(directory + '/' + file.name);
    });

  // Move out of the directory
  cd('..');
}