# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: contact-center-insights
on:
  push:
    branches:
    - main
    paths:
    - 'contact-center-insights/**'
    - '.github/workflows/contact-center-insights.yaml'
  pull_request:
    paths:
    - 'contact-center-insights/**'
    - '.github/workflows/contact-center-insights.yaml'
  pull_request_target:
    types: [labeled]
    paths:
    - 'contact-center-insights/**'
    - '.github/workflows/contact-center-insights.yaml'
  schedule:
  - cron:  '0 0 * * 0'
jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.event.action != 'labeled' || github.event.label.name == 'actions:force-run'
    uses: ./.github/workflows/test.yaml
    with:
      name: 'contact-center-insights'
      path: 'contact-center-insights'
  flakybot:
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.event_name == 'schedule' && always() # always() submits logs even if tests fail
    uses: ./.github/workflows/flakybot.yaml
    needs: [test]
