# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: document-ai
on:
  push:
    branches:
    - main
    paths:
    - 'document-ai/**'
    - '.github/workflows/document-ai.yaml'
    - '.github/workflows/test.yaml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - labeled
    paths:
    - 'document-ai/**'
    - '.github/workflows/document-ai.yaml'
    - '.github/workflows/test.yaml'
  schedule:
  - cron: '0 0 * * 0'
jobs:
  test:
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.event.action != 'labeled' || github.event.label.name == 'actions:force-run'
    uses: ./.github/workflows/test.yaml
    with:
      name: 'document-ai'
      path: 'document-ai'
