name: iam-deny
on:
  push:
    branches:
    - main
    paths:
    - 'iam/deny/**'
  pull_request:
    paths:
    - 'iam/deny/**'
  pull_request_target:
    types: [labeled]
  schedule:
  - cron:  '0 0 * * 0'
jobs:
  test:
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'actions:force-run' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: 'write'
      pull-requests: 'write'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - uses: google-github-actions/auth@v0.8.0
      with:
        workload_identity_provider: 'projects/949737848314/locations/global/workloadIdentityPools/iam-deny-test-pool/providers/iam-deny-test-provider'
        service_account: 'kokoro-ca@isakovf-iam-deny-samples.iam.gserviceaccount.com'
        create_credentials_file: 'true'
        access_token_lifetime: 600s
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm install
      working-directory: iam/deny
    - run: npm test
      working-directory: iam/deny
      env:
        MOCHA_REPORTER_SUITENAME: iam_deny
        MOCHA_REPORTER_OUTPUT: iam_deny_sponge_log.xml
        MOCHA_REPORTER: xunit
    - if: ${{ github.event.action == 'labeled' && github.event.label.name == 'actions:force-run' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            await github.rest.issues.removeLabel({
              name: 'actions:force-run',
              owner: 'GoogleCloudPlatform',
              repo: 'nodejs-docs-samples',
              issue_number: context.payload.pull_request.number
            });
          } catch (e) {
            if (!e.message.includes('Label does not exist')) {
              throw e;
            }
          }
    - if: ${{ github.event_name == 'schedule' && always() }}
      run: |
        curl https://github.com/googleapis/repo-automation-bots/releases/download/flakybot-1.1.0/flakybot -o flakybot -s -L
        chmod +x ./flakybot
        ./flakybot --repo GoogleCloudPlatform/nodejs-docs-samples --commit_hash ${{github.sha}} --build_url https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
